version: '3'

services:
  dynamo:
    image: cnadiminti/dynamodb-local
    ports:
      - 8000:8000

  dynamo-gui:
    image: yamitzky/dynamodb-gui
    environment:
      - DYNAMO_ENDPOINT=http://dynamo:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamo
